package com.icexxx.util;

import java.util.HashMap;
import java.util.Map;

/**
 * 拼音工具类 对不在音序表范围的常用字进行特殊处理
 * 
 * @author IceWater
 * @version 2.1
 */
public class IcePinyin {
    private static Map<String, String> map;

    /**
     * 获取汉字对应的拼音
     * 
     * @param str 单个汉字
     * @return 汉字对应的拼音
     * @since 2.1
     */
    public static String getPinyin(String str) {
        if (map == null) {
            map = init();
        }
        return map.get(str);
    }

    private static Map<String, String> init() {
        Map<String, String> map = new HashMap<String, String>();
        map.put("砹", "ai");// 砹
        map.put("霭", "ai");// 霭
        map.put("桉", "an");// 桉
        map.put("铵", "an");// 铵
        map.put("黯", "an");// 黯
        map.put("坳", "ao");// 坳
        map.put("螯", "ao");// 螯
        map.put("钯", "ba");// 钯
        map.put("钣", "ban");// 钣
        map.put("趵", "bao");// 趵
        map.put("陂", "bei");// 陂
        map.put("匕", "bi");// 匕
        map.put("妣", "bi");// 妣
        map.put("婢", "bi");// 婢
        map.put("弼", "bi");// 弼
        map.put("铋", "bi");// 铋
        map.put("汴", "bian");// 汴
        map.put("蝙", "bian");// 蝙
        map.put("婊", "biao");// 婊
        map.put("蹩", "bie");// 蹩
        map.put("膑", "bin");// 膑
        map.put("摒", "bing");// 摒
        map.put("禀", "bing");// 禀
        map.put("亳", "bo");// 亳
        map.put("钚", "bu");// 钚
        map.put("钸", "bu");// 钸
        map.put("汊", "cha");// 汊
        map.put("猹", "cha");// 猹
        map.put("钗", "chai");// 钗
        map.put("婵", "chan");// 婵
        map.put("孱", "chan");// 孱
        map.put("禅", "chan");// 禅
        map.put("娼", "chang");// 娼
        map.put("嫦", "chang");// 嫦
        map.put("徜", "chang");// 徜
        map.put("怅", "chang");// 怅
        map.put("枨", "cheng");// 枨
        map.put("蚩", "chi");// 蚩
        map.put("怵", "chu");// 怵
        map.put("杵", "chu");// 杵
        map.put("踹", "chuai");// 踹
        map.put("氚", "chuan");// 氚
        map.put("钏", "chuan");// 钏
        map.put("怆", "chuang");// 怆
        map.put("龊", "chuo");// 龊
        map.put("祠", "ci");// 祠
        map.put("猝", "cu");// 猝
        map.put("氘", "dao");// 氘
        map.put("钿", "dian");// 钿
        map.put("貂", "diao");// 貂
        map.put("氡", "dong");// 氡
        map.put("窦", "dou");// 窦
        map.put("蚪", "dou");// 蚪
        map.put("钭", "dou");// 钭
        map.put("笃", "du");// 笃
        map.put("沌", "dun");// 沌
        map.put("盹", "dun");// 盹
        map.put("鳄", "e");// 鳄
        map.put("铒", "er");// 铒
        map.put("梵", "fan");// 梵
        map.put("钫", "fang");// 钫
        map.put("妃", "fei");// 妃
        map.put("翡", "fei");// 翡
        map.put("霏", "fei");// 霏
        map.put("鼢", "fen");// 鼢
        map.put("俸", "feng");// 俸
        map.put("沣", "feng");// 沣
        map.put("匐", "fu");// 匐
        map.put("蝮", "fu");// 蝮
        map.put("驸", "fu");// 驸
        map.put("尬", "ga");// 尬
        map.put("旮", "ga");// 旮
        map.put("钆", "ga");// 钆
        map.put("丐", "gai");// 丐
        map.put("尴", "gan");// 尴
        map.put("杲", "gao");// 杲
        map.put("肱", "gong");// 肱
        map.put("蚣", "gong");// 蚣
        map.put("汩", "gu");// 汩
        map.put("钴", "gu");// 钴
        map.put("卦", "gua");// 卦
        map.put("盥", "guan");// 盥
        map.put("晷", "gui");// 晷
        map.put("帼", "guo");// 帼
        map.put("聒", "guo");// 聒
        map.put("蚶", "han");// 蚶
        map.put("沆", "hang");// 沆
        map.put("昊", "hao");// 昊
        map.put("泓", "hong");// 泓
        map.put("闳", "hong");// 闳
        map.put("浒", "hu");// 浒
        map.put("猢", "hu");// 猢
        map.put("骅", "hua");// 骅
        map.put("徨", "huang");// 徨
        map.put("肓", "huang");// 肓
        map.put("荟", "hui");// 荟
        map.put("钬", "huo");// 钬
        map.put("亟", "ji");// 亟
        map.put("岌", "ji");// 岌
        map.put("矶", "ji");// 矶
        map.put("笈", "ji");// 笈
        map.put("荠", "ji");// 荠
        map.put("霁", "ji");// 霁
        map.put("伽", "jia");// 伽
        map.put("囝", "jian");// 囝
        map.put("睑", "jian");// 睑
        map.put("犟", "jiang");// 犟
        map.put("孑", "jie");// 孑
        map.put("桀", "jie");// 桀
        map.put("妗", "jin");// 妗
        map.put("刭", "jing");// 刭
        map.put("婧", "jing");// 婧
        map.put("泾", "jing");// 泾
        map.put("肼", "jing");// 肼
        map.put("鯨", "jing");// 鯨
        map.put("赳", "jiu");// 赳
        map.put("鸠", "jiu");// 鸠
        map.put("钜", "ju");// 钜
        map.put("龃", "ju");// 龃
        map.put("孓", "jue");// 孓
        map.put("觖", "jue");// 觖
        map.put("侃", "kan");// 侃
        map.put("钪", "kang");// 钪
        map.put("闶", "kang");// 闶
        map.put("氪", "ke");// 氪
        map.put("蝌", "ke");// 蝌
        map.put("钶", "ke");// 钶
        map.put("眍", "kou");// 眍
        map.put("鲲", "kun");// 鲲
        map.put("旯", "la");// 旯
        map.put("徕", "lai");// 徕
        map.put("郎", "lang");// 郎
        map.put("铑", "lao");// 铑
        map.put("铹", "lao");// 铹
        map.put("锂", "li");// 锂
        map.put("凉", "liang");// 凉
        map.put("钌", "liao");// 钌
        map.put("冽", "lie");// 冽
        map.put("趔", "lie");// 趔
        map.put("隣", "lin");// 隣
        map.put("囹", "ling");// 囹
        map.put("泠", "ling");// 泠
        map.put("聆", "ling");// 聆
        map.put("浏", "liu");// 浏
        map.put("轳", "lu");// 轳
        map.put("栾", "luan");// 栾
        map.put("囵", "lun");// 囵
        map.put("摞", "luo");// 摞
        map.put("稆", "lv");// 稆
        map.put("闾", "lv");// 闾
        map.put("犸", "ma");// 犸
        map.put("螨", "man");// 螨
        map.put("蟒", "mang");// 蟒
        map.put("莓", "mei");// 莓
        map.put("钔", "men");// 钔
        map.put("咪", "mi");// 咪
        map.put("汨", "mi");// 汨
        map.put("猕", "mi");// 猕
        map.put("沔", "mian");// 沔
        map.put("喵", "miao");// 喵
        map.put("淼", "miao");// 淼
        map.put("咩", "mie");// 咩
        map.put("泯", "min");// 泯
        map.put("闵", "min");// 闵
        map.put("黽", "min");// 黽
        map.put("茗", "ming");// 茗
        map.put("秣", "mo");// 秣
        map.put("貊", "mo");// 貊
        map.put("沐", "mu");// 沐
        map.put("钼", "mu");// 钼
        map.put("捺", "na");// 捺
        map.put("囡", "nan");// 囡
        map.put("恁", "nen");// 恁
        map.put("铌", "ni");// 铌
        map.put("廿", "nian");// 廿
        map.put("聍", "ning");// 聍
        map.put("妞", "niu");// 妞
        map.put("侬", "nong");// 侬
        map.put("驽", "nu");// 驽
        map.put("喏", "nuo");// 喏
        map.put("钕", "nv");// 钕
        map.put("泮", "pan");// 泮
        map.put("怦", "peng");// 怦
        map.put("铍", "pi");// 铍
        map.put("嫖", "piao");// 嫖
        map.put("氕", "pie");// 氕
        map.put("珀", "po");// 珀
        map.put("钋", "po");// 钋
        map.put("钷", "po");// 钷
        map.put("匍", "pu");// 匍
        map.put("憩", "qi");// 憩
        map.put("琪", "qi");// 琪
        map.put("祺", "qi");// 祺
        map.put("倩", "qian");// 倩
        map.put("茜", "qian");// 茜
        map.put("钤", "qian");// 钤
        map.put("妾", "qie");// 妾
        map.put("趄", "qie");// 趄
        map.put("罄", "qing");// 罄
        map.put("裘", "qiu");// 裘
        map.put("鳅", "qiu");// 鳅
        map.put("荃", "quan");// 荃
        map.put("稔", "ren");// 稔
        map.put("蹂", "rou");// 蹂
        map.put("铷", "ru");// 铷
        map.put("朊", "ruan");// 朊
        map.put("偌", "ruo");// 偌
        map.put("仨", "sa");// 仨
        map.put("卅", "sa");// 卅
        map.put("裟", "sha");// 裟
        map.put("霎", "sha");// 霎
        map.put("姗", "shan");// 姗
        map.put("钐", "shan");// 钐
        map.put("殇", "shang");// 殇
        map.put("觞", "shang");// 觞
        map.put("佘", "she");// 佘
        map.put("铈", "shi");// 铈
        map.put("秫", "shu");// 秫
        map.put("铄", "shuo");// 铄
        map.put("汜", "si");// 汜
        map.put("泗", "si");// 泗
        map.put("驷", "si");// 驷
        map.put("忪", "song");// 忪
        map.put("菘", "song");// 菘
        map.put("铊", "ta");// 铊
        map.put("闼", "ta");// 闼
        map.put("肽", "tai");// 肽
        map.put("钛", "tai");// 钛
        map.put("骀", "tai");// 骀
        map.put("忐", "tan");// 忐
        map.put("昙", "tan");// 昙
        map.put("钽", "tan");// 钽
        map.put("傥", "tang");// 傥
        map.put("忑", "te");// 忑
        map.put("殄", "tian");// 殄
        map.put("窕", "tiao");// 窕
        map.put("霆", "ting");// 霆
        map.put("仝", "tong");// 仝
        map.put("佟", "tong");// 佟
        map.put("钍", "tu");// 钍
        map.put("氽", "tun");// 氽
        map.put("沱", "tuo");// 沱
        map.put("沲", "tuo");// 沲
        map.put("罔", "wang");// 罔
        map.put("猥", "wei");// 猥
        map.put("猬", "wei");// 猬
        map.put("玮", "wei");// 玮
        map.put("闱", "wei");// 闱
        map.put("刎", "wen");// 刎
        map.put("汶", "wen");// 汶
        map.put("雯", "wen");// 雯
        map.put("仵", "wu");// 仵
        map.put("妩", "wu");// 妩
        map.put("邬", "wu");// 邬
        map.put("鹉", "wu");// 鹉
        map.put("兮", "xi");// 兮
        map.put("徙", "xi");// 徙
        map.put("禧", "xi");// 禧
        map.put("冼", "xian");// 冼
        map.put("氙", "xian");// 氙
        map.put("筱", "xiao");// 筱
        map.put("骁", "xiao");// 骁
        map.put("貅", "xiu");// 貅
        map.put("栩", "xu");// 栩
        map.put("胥", "xu");// 胥
        map.put("诩", "xu");// 诩
        map.put("铉", "xuan");// 铉
        map.put("巽", "xun");// 巽
        map.put("徇", "xun");// 徇
        map.put("荀", "xun");// 荀
        map.put("娅", "ya");// 娅
        map.put("氩", "ya");// 氩
        map.put("妍", "yan");// 妍
        map.put("闫", "yan");// 闫
        map.put("杳", "yao");// 杳
        map.put("窈", "yao");// 窈
        map.put("邺", "ye");// 邺
        map.put("佚", "yi");// 佚
        map.put("怡", "yi");// 怡
        map.put("轶", "yi");// 轶
        map.put("钇", "yi");// 钇
        map.put("驿", "yi");// 驿
        map.put("氤", "yin");// 氤
        map.put("蚓", "yin");// 蚓
        map.put("龈", "yin");// 龈
        map.put("嬴", "ying");// 嬴
        map.put("罂", "ying");// 罂
        map.put("攸", "you");// 攸
        map.put("莜", "you");// 莜
        map.put("铕", "you");// 铕
        map.put("妪", "yu");// 妪
        map.put("竽", "yu");// 竽
        map.put("纡", "yu");// 纡
        map.put("钰", "yu");// 钰
        map.put("龉", "yu");// 龉
        map.put("沅", "yuan");// 沅
        map.put("昀", "yun");// 昀
        map.put("氲", "yun");// 氲
        map.put("崽", "zai");// 崽
        map.put("啧", "ze");// 啧
        map.put("钊", "zhao");// 钊
        map.put("柘", "zhe");// 柘
        map.put("蜇", "zhe");// 蜇
        map.put("圳", "zhen");// 圳
        map.put("钲", "zheng");// 钲
        map.put("咫", "zhi");// 咫
        map.put("祗", "zhi");// 祗
        map.put("豸", "zhi");// 豸
        map.put("轵", "zhi");// 轵
        map.put("踵", "zhong");// 踵
        map.put("纣", "zhou");// 纣
        map.put("纣", "zhou");// 纣
        map.put("竺", "zhu");// 竺
        map.put("舳", "zhu");// 舳
        map.put("姊", "zi");// 姊
        map.put("梓", "zi");// 梓
        map.put("秭", "zi");// 秭
        map.put("龇", "zi");// 龇
        map.put("驺", "zou");// 驺
        map.put("阼", "zuo");// 阼
        return map;
    }
}
